### ISSUE TITLE
Error message using "Overlay raster metrics (Polygons)"

### ISSUE THREAD

**Issue by mrobins18** [Martin-Jung/LecoS#20]
Hello,

I am using the recent release of LecoS (3.0) with QGIS 3.6.3. When trying to run an operation with "overlay raster metrics" to calculate landcover within a vector overlay (a shapefile of 1000m2 buffers) I get the following error message. 

_________________________________________________________________________________

Traceback (most recent call last):
File "C:/Users/mrobinson/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LecoS\lecos_sextantealgorithms.py", line 821, in processAlgorithm
bat = pov.BatchConverter(inputFilename,vectorFilename,None)
File "C:/Users/mrobinson/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LecoS\landscape_polygonoverlay.py", line 121, in __init__
self.lyr = self.shapef.GetLayer()
AttributeError: 'NoneType' object has no attribute 'GetLayer'

Execution failed after 0.03 seconds

___________________________________________________________________________________

I eventually want to do this as  a batch process, calculating multiple metrics. 

Thanks in advance!

**Comment by Martin-Jung** [comment]
This error usually pops up if files are not properly loaded (e.g. cannot be read from harddisk).
Please check the following:
- Ensure that the projection of both raster and vector polygons is identical
- Create physical copy (not a temporary one) of each file on your harddrive. The reason is that the python script within LecoS reads the file from harddisk ignoring QGIS entirely.

If this still fails, then please provide a small subset of your data (vector and raster) as test dataset and upload it here, so that the error can be reproduced.

**Comment by mrobins18** [comment]
Thanks for your response. 

- I ensured that both the raster and vector had the same projections.
- I double checked that both files are permanent and located on my harddrive.   

In reattempting the process, I received the same error message. 

I have attached some sample data to this thread (vector and raster files) in the hope that the error can be reproduced. 


[test data.zip](https://github.com/Martin-Jung/LecoS/files/3311775/test.data.zip)

**Comment by Martin-Jung** [comment]
Failed to reproduce the error on my machine (3.6.3 QGIS) using the LecoS Processing toolbox and polygon overlay. 
See screenshot.
![image](https://user-images.githubusercontent.com/3788377/59880824-499b0700-93ae-11e9-93b3-6de2a3028908.png)

**Comment by mrobins18** [comment]
I wonder if it has something to do with how I am entering my parameters?

I have attached a screenshot. 

I am new to LecoS and the overlay raster application, so perhaps you might be able to identify something I'm missing in my initial set-up


![screenshot](https://user-images.githubusercontent.com/52009460/59881710-17b18280-9365-11e9-91f0-de72de62338f.jpg)

**Comment by Martin-Jung** [comment]
You have to set the check at 'classified' since your input raster is a categorical data set. Only uncheck it if you were to use LecoS with continous data such as elevation.
I furthermore entered the class as '8' and the single class metric to land cover proportion.

**Comment by mrobins18** [comment]
Hi Martin,

Thank you for your continued assistance with this. 

I have replicated your parameter entry on the input interface, being sure to check the "raster classified" box. However, I continue to get the the following error message (see screenshot). I have also tried unsuccessfully to run the operation as a batch process. 

My colleague has told me he successfully used the "overlay raster" tool for the same dataset, although he mentioned he was using an older release of the plugin with QGIS 2.1.8. 

I am wondering if the issues I'm encountering might have something to do with this being a newer release version in concert with the packages I've included in my custom QGIS install. I have ensured that scipy, numpy, and PIL were included (for python 3). 

I will continue to troubleshoot, but please let me know if you have any further suggestions. 

Thanks again!


![QGIS LecoS Error](https://user-images.githubusercontent.com/52009460/59886053-569a0500-9372-11e9-8b17-1f39695f092e.jpg)

**Comment by mrobins18** [comment]
Update:

I have since had success with the "Overlay Raster Metrics (polygons)" tool and am now able to successfully process a raster one class at a time, saving each output as a csv file. However, **I am unable to complete the same operation using the "run as batch process" option**.  I have attached a screen shot of both my parameter entry and the subsequent error message I receive. I have also attached my raster and vector files to see if the error can be repeated. 

![batch process error_june 23](https://user-images.githubusercontent.com/52009460/59983712-cf4dcb00-95d7-11e9-8e33-e296c1941020.jpg)
[test data.zip](https://github.com/Martin-Jung/LecoS/files/3318725/test.data.zip)



With 11 classes in my landscape raster and 6+ landscape metrics to calculate across multiple vector overlay files, It would be ideal if I could do batch processing. However, if no immediate resolution can be reached, I can at least do individual processing in the interim.

**Comment by Matt-RS** [comment]
Hi, @mrobins18 I am curious how you managed to solve this? I am currently experiencing exactly the same error. Many thanks

**Comment by mrobins18** [comment]
Hi Matt,

I never fully resolved the issue (i.e could not get batch processing to work).  I was only able to process a single landscape metric at a time. Further, I found I had to save the output as a shapefile rather than a csv. This was because when I saved as a csv it would result in a csv with 2 columns: one labeled "FID" with a continuous sequence of numbers (e.g 1, 2, 3 ....etc) and other with the landscape metric. However, the "FID" column didn't correspond to any of the columns in the attribute table for my input shapefile. As such, I had no way of confidently determining which landscape value belonged to which polygon. When I saved the output as a shapefile however, it would provide the metric values as a new column and a direct correspondence with each polygon's  landscape metric value was clear. 

I then copy and pasted the resulting outputs into an excel file and used the same input shapefile to process other metrics since the metric values would subsequently be overwritten rather than adding a new column to the output's attribute table. 

Given the smaller number of features I was doing the processing on (11 total), this method was manageable, although obviously not efficient.  It would not be feasible for a large number of feature classes.

**Comment by Martin-Jung** [comment]
Just as info:
FID is called a 'Feature ID' and is a (hidden) attribute of all ESRI shapefiles. It corresponds to the row / observation number of your features.

**Comment by Matt-RS** [comment]
I worked out that despite there being no missing data, the fact there was a default no data value was causing the issue. I then removed that option and the first statistic ran correctly. Since then however, I have tried various different ones and the processing never seems to complete (after more than an hour). The raster is 30kmx30km and the grids are 1kmx1km (I increased the scale for these experiments), so although I would expect it to take a little time this does seem excessive. Do you remember roughly how long they took @mrobins18 

Thanks both of you for the information and support.

**Comment by mrobins18** [comment]
Hi Matt,

It took about 10-12 minutes to process a single metric.

**Comment by Matt-RS** [comment]
Hmm OK then perhaps the lengthy processing for my relatively large images is as expected.

@Martin-Jung I am hoping you might be able to help with my next error as it appears to relate to the FID. I will copy the error below but please let me know if there is any other information I can provide that would be of use. Thanks

Traceback (most recent call last):
File "C:/Users/numbe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LecoS\lecos_sextantealgorithms.py", line 842, in processAlgorithm
err, r = bat.go(whatC,cl,pixelSize)
File "C:/Users/numbe/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LecoS\landscape_polygonoverlay.py", line 219, in go
id = poly.GetFID()
AttributeError: 'NoneType' object has no attribute 'GetFID'

Execution failed after 1911.46 seconds

**Comment by Martin-Jung** [comment]
These error's indicate that the shapefile could not been read ( 'NoneType' ), possibly because 
- You are not using a copy that is stored on the harddrive (created for instance as duplicate or temporary output)
- You don't have access rights (read/write) to the shapefile.
- Sth. else has gone wrong. I have seen that error a number of times for other users in the past, but it never occurred for me. So my first guess is always that it is system-specific setup issue.

Sorry to be not more of help, but I haven't got much time for LecoS development these days...

**Comment by Matt-RS** [comment]
Sadly it must be the third option. I will try an older version of QGIS at least, just in case that makes a difference.
No worries, it's nice to have such a quick response at least. Thanks

**Comment by CWen001** [comment]
After testing a bunch of my data using different settings, I have concluded a few experiences workable, in addition to the suggestions above.

(1) The grid vector has to be a shapefile. Neither geopackage nor geojson works.
(2) The CRS of the vector and the raster has to be the same AND to be projected. EPSG 4326 doesn't work, at least for me.
(3) Double-check the nodata value for the raster.
(4) LecoS doesn't support multipolygon so far.

**Comment by xxl-qiu** [comment]
@Martin-Jung Hellow,l don't understand how to solve the problem ,such as using LecoS Processing Toolbox.

**Comment by xxl-qiu** [comment]
@mrobins18 Hellow,How didi you solve the problem.

**Comment by FloMee** [comment]
Hello, 

This is my first post on GitHub and my knowledge on programming is extremely low-lewel but I found an ugly workaround for the problem reported here that i wanted to share with you.
I am using LecoS 3.0 with QGIS 3.14. On some point I realized that the parameter VECTOR_GRID consists of the source path and the layername separated by |. You can see this on the picture posted by @mrobins on Jun 21, 2019. 
My Solution was to replace `self.vectorPath = self.vector.source()` by `self.vectorPath = self.vector.source().split('|')[0]` in lecos_dlg.py (line 764) and `vectorFilename = vectorlayer.source()` by `vectorFilename = vectorlayer.source().split("|")[0]` in lecos_sextantealgorithms.py (line 807).

This is at least working for me and maybe it is a hint for further problem solving. 
Thanks  @Martin-Jung for this helpful plugin.
